Name:           ros-kinetic-ftm-msgs
Version:        1.0.0
Release:        0%{?dist}
Summary:        ROS ftm_msgs package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/ftm_msgs
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-actionlib-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-std-msgs

%description
The ftm_msgs package provides a recommended interface to be used when developing
FTM application in ROS. The recommended interface consists of three main blocks:
1. FTMSensor - a node that performs periodic FTM measurements for a given list
of FTM Responders. 2. LCIActionServer - An action server node that implements
the following: - Performs an on-demand LCI requests for a given list of FTM
responders - Exposes Action to perform LCI request for a list of responders -
Can be configured to publish LCI measurements results to a topic. If so,
publishes results to ftm/lci topic 3. LCIRegistry - An optional node
implementing the following: - Stores FTM Responders data - Subscribes to ftm/lci
topic in order to update its data structure - Exposes CRUD services ftm_msgs
package provides the definitions of the Messages, Services and Actions needed in
order to implement the architecture described above.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri May 25 2018 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.0.0-0
- Autogenerated by Bloom

